variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
    - build
    - test
    - package
    - deploy


cache:
  paths:
    - .m2/repository
    - target

build_job:
  stage: build
  script: 
    - echo "Maven compile started"
    - "mvn compile"
    - echo "Maven packaging started"
    - "mvn package"

  artifacts: 
   paths: 
      - target/*.war    

test_job:
  stage: test
  script: 
    - echo "Maven test started"
    - "mvn test"

nexus-deploy:
  stage: deploy
  script:
    - 'mvn clean deploy '#-DskipTests -DaltDeploymentRepository=nexus::default::$NEXUS_URL'

    # - 'mvn $MAVEN_OPTS deploy -Dmaven.test.skip=true'


# Deploy_job:
#   stage: deploy
#   script: 
#     - echo "Maven deploy started"
