

variables:
   MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
   MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

image: maven:latest

cache: 
  paths:
     - .m2/repository/
     - target/

stages:
   - build
   - test
   - package
   - deploy

codebuild:
  tags: 
     - build
  stage: build 
  script:   
     - mvn compile 


Codepackage: 
  tags: 
     - build 
  stage: package
  script: 
     - mvn $MAVEN_CLI_OPTS package -Dmaven.test.skip=true 
     - echo "Packaging the code" 
  artifacts: 
     paths: 
        - target/*.war 


Codedeploy: 
  tags: 
     - build 
  stage: deploy 
  script: 
     - mvn $MAVEN_CLI_OPTS deploy -Dmaven.test.skip=true 
     - echo "installing the package in local repository" 

#   script: 
#     - echo "Maven deploy started"
